name: Debug build-and-deploy

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'
          cache: 'npm'

      - name: Make a file
        run: echo "I'm not empty" > some.file

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: What's here?
        run: ls -l

      - name: Is it there?
        run: cat some.file
