name: Debug build-and-deploy

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'
          cache: 'npm'

      - name: What's the diff??
        run: |
          ls -l

          cat .github/workflows/build_and_deploy_and_play.yml

      - name: Take forever
        run: sleep 600
