name: Debug build-and-deploy

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

  push:
    branches:
      # To keep the caches warm maybe
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '16'
          cache: 'npm'

      - name: What's the diff??
        run: |
          ls -l

          cat .github/workflows/build_and_deploy_and_play.yml

      - name: Is auto-merge enabled?
        run: |

          cat << EOF
          ${{ toJSON(github.event.pull_request) }}
          EOF
          echo "Automerge?"
          cat << EOF
          ${{ toJSON(github.event.pull_request.auto_merge) }}
          EOF

      - name: In auto-merge state
        if: ${{ github.event.pull_request.auto_merge }}
        run: echo "Rumor has it that auto-merge is enabled"

      - name: Not in auto-merge state
        if: ${{ !github.event.pull_request.auto_merge }}
        run: echo "Auto-merge is not enabled"

      - name: Take forever
        run: sleep 100
